[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma db seed --preview-feature && npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
  [environments.production]
    envs = { NODE_ENV = "production" }
    
  [environments.development]
    startCommand = "npm run start:dev"
    envs = { NODE_ENV = "development" } 